using System.Collections.Generic;
using CovertActionTools.Core.Models;

namespace CovertActionTools.Core.Importing.Parsers.SpriteSheets
{
    internal class LegacyGuys3SpriteSheetData : BaseLegacySpriteSheetData
    {
        public override string[] Keys => new[] { "GUYS3" };

        public override SimpleImageModel.SpriteSheetData Create()
        {
            return new SimpleImageModel.SpriteSheetData()
            {
                Sprites = new Dictionary<string, SimpleImageModel.Sprite>()
                {
                    { "wall_n", new SimpleImageModel.Sprite() { X = 0, Y = 0, Width = 16, Height = 16 } },
                    { "wall_e", new SimpleImageModel.Sprite() { X = 16, Y = 0, Width = 16, Height = 16 } },
                    { "wall_s", new SimpleImageModel.Sprite() { X = 32, Y = 0, Width = 16, Height = 16 } },
                    { "wall_w", new SimpleImageModel.Sprite() { X = 48, Y = 0, Width = 16, Height = 16 } },
                    { "wall_ne", new SimpleImageModel.Sprite() { X = 64, Y = 0, Width = 16, Height = 16 } },
                    { "wall_se", new SimpleImageModel.Sprite() { X = 80, Y = 0, Width = 16, Height = 16 } },
                    { "wall_sw", new SimpleImageModel.Sprite() { X = 96, Y = 0, Width = 16, Height = 16 } },
                    { "wall_nw", new SimpleImageModel.Sprite() { X = 112, Y = 0, Width = 16, Height = 16 } },
                    { "floor", new SimpleImageModel.Sprite() { X = 0, Y = 112, Width = 16, Height = 16 } },
                    { "door_closed_n", new SimpleImageModel.Sprite() { X = 64, Y = 16, Width = 16, Height = 16 } },
                    { "door_closed_e", new SimpleImageModel.Sprite() { X = 80, Y = 16, Width = 16, Height = 16 } },
                    { "door_closed_s", new SimpleImageModel.Sprite() { X = 96, Y = 16, Width = 16, Height = 16 } },
                    { "door_closed_w", new SimpleImageModel.Sprite() { X = 112, Y = 16, Width = 16, Height = 16 } },
                    { "door_open_n", new SimpleImageModel.Sprite() { X = 64, Y = 32, Width = 16, Height = 16 } },
                    { "door_open_e", new SimpleImageModel.Sprite() { X = 80, Y = 32, Width = 16, Height = 16 } },
                    { "door_open_s", new SimpleImageModel.Sprite() { X = 96, Y = 32, Width = 16, Height = 16 } },
                    { "door_open_w", new SimpleImageModel.Sprite() { X = 112, Y = 32, Width = 16, Height = 16 } },
                    { "chair_s", new SimpleImageModel.Sprite() { X = 128, Y = 0, Width = 16, Height = 16 } },
                    { "chair_w", new SimpleImageModel.Sprite() { X = 144, Y = 0, Width = 16, Height = 16 } },
                    { "chair_n", new SimpleImageModel.Sprite() { X = 160, Y = 0, Width = 16, Height = 16 } },
                    { "chair_e", new SimpleImageModel.Sprite() { X = 176, Y = 0, Width = 16, Height = 16 } },
                    { "computer_n", new SimpleImageModel.Sprite() { X = 192, Y = 0, Width = 16, Height = 16 } },
                    { "computer_s", new SimpleImageModel.Sprite() { X = 224, Y = 0, Width = 16, Height = 16 } },
                    { "printer_w", new SimpleImageModel.Sprite() { X = 208, Y = 0, Width = 16, Height = 16 } },
                    { "printer_e", new SimpleImageModel.Sprite() { X = 242, Y = 0, Width = 16, Height = 16 } },
                    { "wall_cabinet_closed_s", new SimpleImageModel.Sprite() { X = 128, Y = 16, Width = 16, Height = 16 } },
                    { "wall_cabinet_closed_w", new SimpleImageModel.Sprite() { X = 144, Y = 16, Width = 16, Height = 16 } },
                    { "wall_cabinet_closed_n", new SimpleImageModel.Sprite() { X = 160, Y = 16, Width = 16, Height = 16 } },
                    { "wall_cabinet_closed_e", new SimpleImageModel.Sprite() { X = 176, Y = 16, Width = 16, Height = 16 } },
                    { "wall_cabinet_open_s", new SimpleImageModel.Sprite() { X = 128, Y = 32, Width = 16, Height = 16 } },
                    { "wall_cabinet_open_w", new SimpleImageModel.Sprite() { X = 144, Y = 32, Width = 16, Height = 16 } },
                    { "wall_cabinet_open_n", new SimpleImageModel.Sprite() { X = 160, Y = 32, Width = 16, Height = 16 } },
                    { "wall_cabinet_open_e", new SimpleImageModel.Sprite() { X = 176, Y = 32, Width = 16, Height = 16 } },
                    { "wall_floor_safe_closed_s", new SimpleImageModel.Sprite() { X = 192, Y = 16, Width = 16, Height = 16 } },
                    { "wall_floor_safe_open_s", new SimpleImageModel.Sprite() { X = 192, Y = 32, Width = 16, Height = 16 } },
                    { "wall_safe_closed_w", new SimpleImageModel.Sprite() { X = 208, Y = 16, Width = 16, Height = 16 } },
                    { "wall_safe_closed_e", new SimpleImageModel.Sprite() { X = 240, Y = 16, Width = 16, Height = 16 } },
                    { "wall_safe_open_w", new SimpleImageModel.Sprite() { X = 208, Y = 32, Width = 16, Height = 16 } },
                    { "wall_safe_open_e", new SimpleImageModel.Sprite() { X = 240, Y = 32, Width = 16, Height = 16 } },
                    { "wall_picture_closed_n", new SimpleImageModel.Sprite() { X = 224, Y = 16, Width = 16, Height = 16 } },
                    { "wall_picture_open_n", new SimpleImageModel.Sprite() { X = 224, Y = 32, Width = 16, Height = 16 } },
                    { "desk_closed_s_1", new SimpleImageModel.Sprite() { X = 0, Y = 16, Width = 16, Height = 16 } },
                    { "desk_closed_s_2", new SimpleImageModel.Sprite() { X = 16, Y = 16, Width = 16, Height = 16 } },
                    { "desk_open_s_1", new SimpleImageModel.Sprite() { X = 0, Y = 32, Width = 16, Height = 16 } },
                    { "desk_open_s_2", new SimpleImageModel.Sprite() { X = 16, Y = 32, Width = 16, Height = 16 } },
                    { "desk_closed_n_1", new SimpleImageModel.Sprite() { X = 32, Y = 16, Width = 16, Height = 16 } },
                    { "desk_closed_n_2", new SimpleImageModel.Sprite() { X = 48, Y = 16, Width = 16, Height = 16 } },
                    { "desk_open_n_1", new SimpleImageModel.Sprite() { X = 32, Y = 32, Width = 16, Height = 16 } },
                    { "desk_open_n_2", new SimpleImageModel.Sprite() { X = 48, Y = 32, Width = 16, Height = 16 } },
                    { "server_s", new SimpleImageModel.Sprite() { X = 0, Y = 48, Width = 16, Height = 16 } },
                    { "server_w", new SimpleImageModel.Sprite() { X = 16, Y = 48, Width = 16, Height = 16 } },
                    { "server_n", new SimpleImageModel.Sprite() { X = 32, Y = 48, Width = 16, Height = 16 } },
                    { "server_e", new SimpleImageModel.Sprite() { X = 48, Y = 48, Width = 16, Height = 16 } },
                    { "table_1", new SimpleImageModel.Sprite() { X = 64, Y = 48, Width = 16, Height = 16 } },
                    { "table_2", new SimpleImageModel.Sprite() { X = 80, Y = 48, Width = 16, Height = 16 } },
                    { "sofa_n_1", new SimpleImageModel.Sprite() { X = 96, Y = 48, Width = 16, Height = 16 } },
                    { "sofa_n_2", new SimpleImageModel.Sprite() { X = 112, Y = 48, Width = 16, Height = 16 } },
                    { "sofa_s_1", new SimpleImageModel.Sprite() { X = 128, Y = 48, Width = 16, Height = 16 } },
                    { "sofa_s_2", new SimpleImageModel.Sprite() { X = 144, Y = 48, Width = 16, Height = 16 } },
                    { "wall_record_s", new SimpleImageModel.Sprite() { X = 224, Y = 48, Width = 16, Height = 16 } },
                    { "wall_aquarium_n", new SimpleImageModel.Sprite() { X = 256, Y = 48, Width = 16, Height = 16 } },
                    { "plant_1", new SimpleImageModel.Sprite() { X = 272, Y = 0, Width = 16, Height = 16 } },
                    { "plant_2", new SimpleImageModel.Sprite() { X = 304, Y = 0, Width = 16, Height = 16 } },
                    { "mini_floor", new SimpleImageModel.Sprite() { X = 54, Y = 140, Width = 3, Height = 3 } },
                    { "mini_wall_n", new SimpleImageModel.Sprite() { X = 0, Y = 128, Width = 3, Height = 3 } },
                    { "mini_wall_e", new SimpleImageModel.Sprite() { X = 3, Y = 128, Width = 3, Height = 3 } },
                    { "mini_wall_s", new SimpleImageModel.Sprite() { X = 6, Y = 128, Width = 3, Height = 3 } },
                    { "mini_wall_w", new SimpleImageModel.Sprite() { X = 9, Y = 128, Width = 3, Height = 3 } },
                    { "mini_wall_ne", new SimpleImageModel.Sprite() { X = 12, Y = 128, Width = 3, Height = 3 } },
                    { "mini_wall_se", new SimpleImageModel.Sprite() { X = 15, Y = 128, Width = 3, Height = 3 } },
                    { "mini_wall_sw", new SimpleImageModel.Sprite() { X = 18, Y = 128, Width = 3, Height = 3 } },
                    { "mini_wall_nw", new SimpleImageModel.Sprite() { X = 21, Y = 128, Width = 3, Height = 3 } },
                    { "mini_chair_s", new SimpleImageModel.Sprite() { X = 24, Y = 128, Width = 3, Height = 3 } },
                    { "mini_chair_w", new SimpleImageModel.Sprite() { X = 27, Y = 128, Width = 3, Height = 3 } },
                    { "mini_chair_n", new SimpleImageModel.Sprite() { X = 30, Y = 128, Width = 3, Height = 3 } },
                    { "mini_chair_e", new SimpleImageModel.Sprite() { X = 33, Y = 128, Width = 3, Height = 3 } },
                    { "mini_computer_n", new SimpleImageModel.Sprite() { X = 36, Y = 128, Width = 3, Height = 3 } },
                    { "mini_printer_e", new SimpleImageModel.Sprite() { X = 39, Y = 128, Width = 3, Height = 3 } },
                    { "mini_computer_s", new SimpleImageModel.Sprite() { X = 42, Y = 128, Width = 3, Height = 3 } },
                    { "mini_printer_w", new SimpleImageModel.Sprite() { X = 45, Y = 128, Width = 3, Height = 3 } },
                    { "mini_plant_1", new SimpleImageModel.Sprite() { X = 51, Y = 128, Width = 3, Height = 3 } },
                    { "mini_plant_2", new SimpleImageModel.Sprite() { X = 57, Y = 128, Width = 3, Height = 3 } },
                    { "mini_desk_s_1", new SimpleImageModel.Sprite() { X = 0, Y = 131, Width = 3, Height = 3 } },
                    { "mini_desk_s_2", new SimpleImageModel.Sprite() { X = 3, Y = 131, Width = 3, Height = 3 } },
                    { "mini_desk_n_1", new SimpleImageModel.Sprite() { X = 6, Y = 131, Width = 3, Height = 3 } },
                    { "mini_desk_n_2", new SimpleImageModel.Sprite() { X = 9, Y = 131, Width = 3, Height = 3 } },
                    { "mini_door_n", new SimpleImageModel.Sprite() { X = 12, Y = 131, Width = 3, Height = 3 } },
                    { "mini_door_e", new SimpleImageModel.Sprite() { X = 15, Y = 131, Width = 3, Height = 3 } },
                    { "mini_door_s", new SimpleImageModel.Sprite() { X = 18, Y = 131, Width = 3, Height = 3 } },
                    { "mini_door_w", new SimpleImageModel.Sprite() { X = 21, Y = 131, Width = 3, Height = 3 } },
                    { "mini_cabinet_s", new SimpleImageModel.Sprite() { X = 24, Y = 131, Width = 3, Height = 3 } },
                    { "mini_cabinet_w", new SimpleImageModel.Sprite() { X = 27, Y = 131, Width = 3, Height = 3 } },
                    { "mini_cabinet_n", new SimpleImageModel.Sprite() { X = 30, Y = 131, Width = 3, Height = 3 } },
                    { "mini_cabinet_e", new SimpleImageModel.Sprite() { X = 33, Y = 131, Width = 3, Height = 3 } },
                    { "mini_floor_safe_s", new SimpleImageModel.Sprite() { X = 36, Y = 131, Width = 3, Height = 3 } },
                    { "mini_safe_w", new SimpleImageModel.Sprite() { X = 39, Y = 131, Width = 3, Height = 3 } },
                    { "mini_picture_n", new SimpleImageModel.Sprite() { X = 42, Y = 131, Width = 3, Height = 3 } },
                    { "mini_safe_e", new SimpleImageModel.Sprite() { X = 45, Y = 131, Width = 3, Height = 3 } },
                    { "mini_server_s", new SimpleImageModel.Sprite() { X = 0, Y = 137, Width = 3, Height = 3 } },
                    { "mini_server_w", new SimpleImageModel.Sprite() { X = 3, Y = 137, Width = 3, Height = 3 } },
                    { "mini_server_n", new SimpleImageModel.Sprite() { X = 6, Y = 137, Width = 3, Height = 3 } },
                    { "mini_server_e", new SimpleImageModel.Sprite() { X = 9, Y = 137, Width = 3, Height = 3 } },
                    { "mini_table_1", new SimpleImageModel.Sprite() { X = 12, Y = 137, Width = 3, Height = 3 } },
                    { "mini_table_2", new SimpleImageModel.Sprite() { X = 15, Y = 137, Width = 3, Height = 3 } },
                    { "mini_sofa_n_1", new SimpleImageModel.Sprite() { X = 18, Y = 137, Width = 3, Height = 3 } },
                    { "mini_sofa_n_2", new SimpleImageModel.Sprite() { X = 21, Y = 137, Width = 3, Height = 3 } },
                    { "mini_sofa_s_1", new SimpleImageModel.Sprite() { X = 24, Y = 137, Width = 3, Height = 3 } },
                    { "mini_sofa_s_2", new SimpleImageModel.Sprite() { X = 27, Y = 137, Width = 3, Height = 3 } },
                    { "mini_record_s", new SimpleImageModel.Sprite() { X = 42, Y = 137, Width = 3, Height = 3 } },
                    { "mini_aquarium_n", new SimpleImageModel.Sprite() { X = 48, Y = 137, Width = 3, Height = 3 } },
                }
            };
        }
    }
}
