name: Build Application

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]

jobs:
  windows:
    strategy:
      runs-on: ubuntu-latest
      name: Build for Windows
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
            cache: true
        - name: publish
          run: dotnet publish -c Release -r win-x64 --artifacts-path "../publish"
          working-directory: ./src
        - name: Upload
          run: ls -la
          working-directory: ../publish/publish/CovertActionTools.App/release_win-x64