name: Build Application

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: ubuntu-latest
    name: Build for Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: publish
        run: dotnet publish -c Release -r win-x64 --artifacts-path "../publish"
        working-directory: ./src
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: |
            /home/runner/work/CovertActionTools/CovertActionTools/publish/publish/CovertActionTools.App/release_win-x64
          if-no-files-found: error